### ISSUE TITLE
Change the plots color

### ISSUE THREAD

**Issue by joaofelipecsantos** [xcube-dev/xcube-viewer#97] opened 2019-11-04 16:43 UTC
** Describing the issue**
I am running the xcube-viewer and I am selecting one point on the map.

![ticket02_01](https://user-images.githubusercontent.com/32440152/68139077-ce378d80-ff29-11e9-9fd2-d5aa83ea919d.jpg)

The plot is generated correctly.

Then I changed my variable and I use the option to create another plot based on the point used before. The plot for the new variable has the same color of the variable before. It happens for all the variables that I have and apply the plot symbol to keep the same point.

![ticket02_02](https://user-images.githubusercontent.com/32440152/68139169-f7f0b480-ff29-11e9-9262-42d47e57da01.jpg)

** What I was expecting**
I was expecting to have plots with different colors as when I click on the map to create a plot and click again to create a new plot.
Or I was expecting the possibility to change the color after the plot appears by right click or some box in the viewer.

** Extra info**
I am running xcube-viewer on Linux Ubuntu 18.04.
I updated xcube-viewer on 30/10/2019.

Thank you, Joao.

**Comment by forman** [comment] 2019-11-07 11:33
@joaofelipecsantos, this is expected behaviour as the plot's color should be the same as the point's color.

Do you prefer having colours assigned to variables rather than points / polygons?

**Comment by joaofelipecsantos** [comment] 2019-11-08 08:27
Hello Norman,

**I understood and I agree with your point of view (plot's color should be the same as the point's color).**

But, the possibility to change the plot color in the future would be interesting, for example:
- If I have Chla DL with S2plus data and 1W resampled `(DL02_U00_S2_1W)` **+** Chla DL with S3plus data and 1W resampled `(DL02_U00_S3_1W)` for the same point. Both Chla DLs will appear with the same time step in the same graph with the same color and almost the same values. Then would be nice the possibility to change the color from one of the them.

But, this is for a very advanced version and maybe the user with the imaginary case above will prefer to work in the Jupyter notebook.

Resuming, is good as it is now.
Thank you for the reply, regards.

**Comment by forman** [comment] 2019-11-15 10:11
@joaofelipecsantos, we'll leave this issue open and may implement this later. You are also welcome to send a pull request!

**Comment by rabaneda** [comment] 2020-02-10 16:30
@joaofelipecsantos , @forman  I also understand that if we want to link the point on the map with the line they must have same color. But, this is not ideal when we look at the graph.

So, what about changing the line style instead of the color? For example, if the second variable is at the same point use a dotted line. Then, we'll be able to distinguish between lines in the graph.

Since the code is in Typescript I'm afraid I cannot do a pull request myself.

**Closed** 2024-07-19 06:40 UTC
Labels: enhancement, DCS4COP
